use isp_db;
show databases;
show tables;
use isp_2;
select * from isps;
select * from isp_2.plans;
select * from plans;
select * from employees;
describe hardware_details;
describe billing_details;
describe employee_permissions;
show create table employees;

select * from customers;
select * from billing_details;
select * from hardware_details;
select * from subscriptions;
select * from bills;
select * from bill_items;
select * from payments;
select * from service_areas;
select * from balance_sheet;
