spring:
  datasource:
    url: jdbc:mysql://localhost:3306/isp_db
    username: isp_local
    password: isp_pwd
  jpa:
    hibernate:
      ddl-auto=create-drop: none
  cache:
    type: redis
    redis:
      time-to-live: 300000
  redis:
    host: localhost
    port: 6379

jwt:
  secret: ${JWT_SECRET}
  expirationDateInMs: 60000
  refreshExpirationDateInMs: 300000