## Multipart config
spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 100MB
      max-request-size: 115MB

server:
  port: 9988
file:
  upload:
    location: /users/vendors


bill-generator:
  cron:
    expression: 0 * 1 * * *